{
 "title": "Prometheus Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(prometheus_demo_request_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(prometheus_demo_request_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(prometheus_demo_request_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_demo_request_count[5m])) by (path, code)",
     "legendFormat": "{{path}}, {{code}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 21 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(prometheus_demo_request_count{code=\"500\"}[5m])) / sum(rate(prometheus_demo_request_count[5m])) "
    }
   ]
  },
  {
   "title": "Total Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_demo_request_count[5m]))",
     "legendFormat": "Request Rate"
    }
   ]
  }
 ]
}