apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-people
  annotations:
    ad.datadoghq.com/{{ .Chart.Name }}.check_names: '["prometheus"]'
    ad.datadoghq.com/{{ .Chart.Name }}.init_configs: '[{}]'
    ad.datadoghq.com/{{ .Chart.Name }}.instances: '[{"prometheus_url": "http://%%host%%:8080/metrics","namespace": "test","metrics": ["*"],"type_overrides": {}}]'
  labels:
    app.kubernetes.io/name: {{ include "prometheus-demo.name" . }}
    helm.sh/chart: {{ include "prometheus-demo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prometheus-demo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        ad.datadoghq.com/{{ .Chart.Name }}.check_names: '["prometheus"]'
        ad.datadoghq.com/{{ .Chart.Name }}.init_configs: '[{}]'
        ad.datadoghq.com/{{ .Chart.Name }}.instances: '[{"prometheus_url": "http://%%host%%:8080/metrics","namespace": "promdemo","metrics": ["*"], "send_histogram_buckets": true, "type_overrides": {"prometheus_demo_request_latency_seconds": "histogram"}}]'
      labels:
        app.kubernetes.io/name: {{ include "prometheus-demo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: REDIS_ADDR
            value: {{ .Values.redisAddress }}
          - name: RELEASE
            value: "{{ .Release.Revision }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
