apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: hello-people-redis
    helm.sh/chart: {{ include "prometheus-demo.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: bitnami/redis:5.0
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis
